web:
  build: .
  ports:
    - "3000:3000"

mq:
  image: rabbitmq:3.7.5-management
  ports:
    - "5672:5672"
    - "15672:15672"
  environment:
    RABBITMQ_DEFAULT_USER: admin
    RABBITMQ_DEFAULT_PASS: admin